"""address and style change

Revision ID: 39ce3dc5e758
Revises: 57294821020a
Create Date: 2024-07-27 19:43:13.533065

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '39ce3dc5e758'
down_revision: Union[str, None] = '57294821020a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email_address', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user__user.id'], name=op.f('fk_address_user_id_user__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_address'))
    )
    op.alter_column('user__user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user__user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user__user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user__user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('address')
    # ### end Alembic commands ###
