"""add password

Revision ID: 55a77e9c781c
Revises: 6354c2279afc
Create Date: 2024-10-06 18:29:07.631652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55a77e9c781c'
down_revision: Union[str, None] = '6354c2279afc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user__user', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__user', 'password')
    # ### end Alembic commands ###
