"""nullable names and age in user

Revision ID: 6354c2279afc
Revises: 39ce3dc5e758
Create Date: 2024-10-06 18:25:19.625639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6354c2279afc'
down_revision: Union[str, None] = '39ce3dc5e758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_address_email_address'), 'address', ['email_address'])
    op.alter_column('user__user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user__user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user__user', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user__user', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('uq_address_email_address'), 'address', type_='unique')
    # ### end Alembic commands ###
