"""test

Revision ID: 75ad48cbd66e
Revises: 7f28156bf52a
Create Date: 2024-11-22 17:25:40.265903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75ad48cbd66e'
down_revision: Union[str, None] = '7f28156bf52a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__book',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user__book'))
    )
    op.create_index(op.f('ix_user__book_id'), 'user__book', ['id'], unique=False)
    op.create_table('diary__diary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user__user.id'], name=op.f('fk_diary__diary_user_id_user__user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diary__diary'))
    )
    op.create_index(op.f('ix_diary__diary_id'), 'diary__diary', ['id'], unique=False)
    op.create_index(op.f('ix_diary__diary_user_id'), 'diary__diary', ['user_id'], unique=False)
    op.create_table('user__profile',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user__user.id'], name=op.f('fk_user__profile_user_id_user__user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user__profile')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user__profile_user_id'))
    )
    op.create_index(op.f('ix_user__profile_id'), 'user__profile', ['id'], unique=False)
    op.create_table('user__user_book_table',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['user__book.id'], name=op.f('fk_user__user_book_table_book_id_user__book')),
    sa.ForeignKeyConstraint(['user_id'], ['user__user.id'], name=op.f('fk_user__user_book_table_user_id_user__user')),
    sa.PrimaryKeyConstraint('user_id', 'book_id', name=op.f('pk_user__user_book_table'))
    )
    op.create_table('diary__note',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('diary_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['diary_id'], ['diary__diary.id'], name=op.f('fk_diary__note_diary_id_diary__diary')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diary__note')),
    sa.UniqueConstraint('title', 'diary_id', name=op.f('uq_diary__note_title'))
    )
    op.create_index(op.f('ix_diary__note_diary_id'), 'diary__note', ['diary_id'], unique=False)
    op.create_index(op.f('ix_diary__note_id'), 'diary__note', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diary__note_id'), table_name='diary__note')
    op.drop_index(op.f('ix_diary__note_diary_id'), table_name='diary__note')
    op.drop_table('diary__note')
    op.drop_table('user__user_book_table')
    op.drop_index(op.f('ix_user__profile_id'), table_name='user__profile')
    op.drop_table('user__profile')
    op.drop_index(op.f('ix_diary__diary_user_id'), table_name='diary__diary')
    op.drop_index(op.f('ix_diary__diary_id'), table_name='diary__diary')
    op.drop_table('diary__diary')
    op.drop_index(op.f('ix_user__book_id'), table_name='user__book')
    op.drop_table('user__book')
    # ### end Alembic commands ###
