"""empty message

Revision ID: ab26936f6fb1
Revises: 75ad48cbd66e
Create Date: 2024-11-28 20:40:50.747832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab26936f6fb1'
down_revision: Union[str, None] = '75ad48cbd66e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diary__note', sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diary__note', 'created_at')
    # ### end Alembic commands ###
