name: Default

on: [push]

jobs:
  lint:
    env:
      TEST_DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/test_db
    runs-on: ubuntu-latest
    container: python:3.11
    permissions:
      contents: 'read'
      id-token: 'write'
    services:
      db:
        image: postgres:15.3
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Lint
        run: |
          source .venv/bin/activate
          cd src && ruff check .
      
      - name: Run tests
        run: |
          source .venv/bin/activate
          cd src && pytest